import '../globals.css';
import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { languages } from '@/app/i18n/settings';
import LanguageContext from '@/app/i18n/LanguageContext/server';

const inter = Inter({ subsets: ['latin'] });

/** @ignore */
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/** @ignore */
export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

/** @ignore */
export default function RootLayout({
  children,
  params: { lng },
}: {
  children: React.ReactNode,
  params: { lng: string },
}) {
  return (
    <html lang={lng}>
      <body className={inter.className}>
        <LanguageContext.Provider value={lng}>
          {children}
        </LanguageContext.Provider>
      </body>
    </html>
  );
}
